spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF302P_PROJECT;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Nguyen2006
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect